### ISSUE TITLE
Problem on Windows

### ISSUE THREAD

**Issue by richardmalone** [Virusmater/bandcamp-radio#1]
Hi, love the app although having problems with it on Windows 10.

Installs fine, when I run the command the output is this:

```
    ____________________________
  /|............................|
 | |:        Dojo Cuts         :|
 | |:         El Intro         :|
 | |:     ,-.   _____   ,-.    :|
 | |:    ( `)) [_____] ( `))   :|
 |v|:     `-`   ' ' '   `-`    :|
 |||:     ,______________.     :|
 |||...../::::o::::::o::::\.....|
 |^|..../:::O::::::::::O:::\....|
 |/`---/--------------------`---|
 `.___/ /====/ /=//=/ /====/____/
      `--------------------'
Support Dojo Cuts on https://dojocuts.bandcamp.com
[p]ause, [n]ext and [s]top
Traceback (most recent call last):
  File "C:\Users\Lucky\scoop\apps\python\current\Scripts\bandcamp-radio-script.py", line 33, in <module>
    sys.exit(load_entry_point('bandcamp-radio==0.1', 'console_scripts', 'bandcamp-radio')())
  File "c:\users\lucky\scoop\apps\python\3.9.1\lib\site-packages\bandcamp_radio\__main__.py", line 100, in main
    command = getch.impl()
  File "c:\users\lucky\scoop\apps\python\3.9.1\lib\site-packages\bandcamp_radio\Getch.py", line 35, in __call__
    return msvcrt.getch()
NameError: name 'msvcrt' is not defined
```

I did some digging and I think msvcrt needs to be defined globally.  I put 

`global msvcrt`

Into Getch.py and it runs fine, but is not capturing keystrokes.

Thanks

**Comment by richardmalone** [comment]
I solved the problem.  Using msvcrt.getwch the character output read 

`b'n' ` rather than `n`

Turns out I was using a wide-character terminal (see https://stackoverflow.com/questions/50069553/msvcrt-getch-detects-space-every-time). Using return msvcrt.getwch() works fine.

I made some changes to the code, I will make a pull request.

**Comment by Virusmater** [comment]
Thx Richard,
You PR got merged. I don't have Win machine to test it, but it was never tested at the first place.
